export const eventServiceCategories = [
  'Tiệc cưới',
  'Sinh nhật',
  'Makeup',
  'Trang trí sự kiện',
]

export const eventServices = [
  {
    id: 'wedding-package',
    slug: 'tiec-cuoi-tron-goi',
    name: 'Tiệc cưới trọn gói',
    category: 'Tiệc cưới',
    shortDescription: 'Không gian, âm nhạc, bài trí và trải nghiệm cưới theo phong cách riêng.',
    description: 'Gói tiệc cưới trọn gói mang đến không gian cưới hiện đại, đội ngũ hỗ trợ chuyên nghiệp và quy trình tổ chức rõ ràng từ khâu lên ý tưởng đến thực hiện sự kiện.',
    priceFrom: 18000000,
    duration: '6-10 giờ',
    image: '/assets/bride-jhumar.jpg',
    features: ['Thiết kế không gian theo concept', 'Tư vấn âm thanh và ánh sáng', 'Đội ngũ phục vụ chuyên nghiệp', 'Quản lý timeline sự kiện'],
    isFeatured: true,
  },
  {
    id: 'wedding-decoration',
    slug: 'trang-tri-tiec-cuoi',
    name: 'Trang trí tiệc cưới',
    category: 'Tiệc cưới',
    shortDescription: 'Trang trí cưới tinh tế, ấm cúng và phù hợp với phong cách gia đình.',
    description: 'Trang trí sự kiện cưới được tạo ra theo hình ảnh ý tưởng của bạn, từ màu sắc, chất liệu cho đến điểm nhấn thảm lối đi, bàn tiệc và backdrop.',
    priceFrom: 12000000,
    duration: '3-5 giờ',
    image: '/assets/floral-vine-hands.jpg',
    features: ['Backdrop chụp ảnh', 'Bàn tiệc & sân khấu', 'Chi tiết décor theo chủ đề', 'Đóng gói anh sáng đẹp mắt'],
    isFeatured: true,
  },
  {
    id: 'birthday-party',
    slug: 'tiec-sinh-nhat',
    name: 'Tiệc sinh nhật',
    category: 'Sinh nhật',
    shortDescription: 'Nền tảng tiệc sinh nhật trẻ trung, sáng tạo và đầy cảm xúc.',
    description: 'Từ tiệc gia đình, sinh nhật nhỏ cho trẻ đến tiệc lớn cho công ty và bạn bè, chúng tôi giúp bạn chọn không gian, décor và trải nghiệm phù hợp.',
    priceFrom: 9000000,
    duration: '4-7 giờ',
    image: '/assets/detail-kalire.jpg',
    features: ['Thiết kế chủ đề theo độ tuổi', 'Âm nhạc & ánh sáng', 'Quầy thức uống hoặc món ăn', 'Đội ngũ phục vụ thân thiện'],
    isFeatured: true,
  },
  {
    id: 'birthday-decoration',
    slug: 'trang-tri-sinh-nhat',
    name: 'Trang trí sinh nhật',
    category: 'Sinh nhật',
    shortDescription: 'Bài trí không gian theo chủ đề, màu sắc và phong cách riêng của bạn.',
    description: 'Trang trí tiệc sinh nhật giúp cho không gian trở nên sống động và ấn tượng, phù hợp cho ngày đặc biệt của trẻ em hoặc người lớn.',
    priceFrom: 6500000,
    duration: '2-4 giờ',
    image: '/assets/detail-french-cream.jpg',
    features: ['Backdrop chụp hình', 'Trung tâm sự kiện', 'Bộ dây đèn và bảng tên', 'Phụ kiện theo chủ đề'],
    isFeatured: false,
  },
  {
    id: 'bridal-makeup',
    slug: 'makeup-co-dau',
    name: 'Makeup cô dâu',
    category: 'Makeup',
    shortDescription: 'Makeup cô dâu thanh lịch, tự nhiên và phù hợp với phong cách riêng.',
    description: 'Dịch vụ makeup cô dâu bao gồm tư vấn phong cách, kiểm tra ánh sáng, makeup chuyên nghiệp và chỉnh sửa cuối cùng để bạn rạng rỡ trong ngày trọng đại.',
    priceFrom: 5500000,
    duration: '2-3 giờ',
    image: '/assets/crossed-hands-white.jpg',
    features: ['Tư vấn phong cách', 'Chăm sóc da trước sự kiện', 'Makeup hoàn thiện', 'Kỹ thuật làm đẹp theo ánh sáng'],
    isFeatured: true,
  },
  {
    id: 'party-makeup',
    slug: 'makeup-su-kien',
    name: 'Makeup dự tiệc',
    category: 'Makeup',
    shortDescription: 'Makeup dự tiệc đẹp, bền và phù hợp cho phong cách hiện đại.',
    description: 'Chăm sóc hình ảnh cho các sự kiện, tiệc tối, buổi Portrait và các dịp đòi hỏi phong cách sắc sảo, tự tin và bền màu.',
    priceFrom: 2600000,
    duration: '1.5-2.5 giờ',
    image: '/assets/detail-french-cream.jpg',
    features: ['Makeup theo event', 'Bền màu', 'Tư vấn tone da', 'Sửa chữa cuối cùng'],
    isFeatured: false,
  },
  {
    id: 'event-decoration',
    slug: 'trang-tri-su-kien',
    name: 'Trang trí sự kiện',
    category: 'Trang trí sự kiện',
    shortDescription: 'Trang trí sự kiện theo concept, phù hợp cho tiệc, launch, gala và gặp gỡ.',
    description: 'Tạo không gian sự kiện ấn tượng với bố cục, vật liệu, luồng di chuyển và điểm nhấn thẩm mỹ phù hợp với mục tiêu tổ chức.',
    priceFrom: 11000000,
    duration: '4-8 giờ',
    image: '/assets/process-applying.jpg',
    features: ['Bố cục không gian', 'Âm thanh và ánh sáng', 'Backdrops theo concept', 'Phối hợp với nhà hàng & venue'],
    isFeatured: true,
  },
]

export const formatVnd = (value) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
