export const photographyPackages = [
  {
    id: 'wedding-photo',
    slug: 'anh-cuoi',
    name: 'Ảnh cưới',
    category: 'Ảnh cưới',
    shortDescription: 'Chụp ảnh cưới với phong cách hiện đại, tự nhiên và giàu cảm xúc.',
    description: 'Gói ảnh cưới là lựa chọn hoàn hảo để ghi lại khoảnh khắc trọng đại với ánh sáng đẹp, phong cách tự nhiên và thể hiện cảm xúc của hai bạn.',
    priceFrom: 8500000,
    duration: '4-6 giờ',
    image: '/assets/bride-jhumar.jpg',
    deliverables: ['100+ ảnh đã chỉnh sửa', 'Album online', 'Bộ ảnh highlight', 'Bản JPG chất lượng cao'],
    isFeatured: true,
  },
  {
    id: 'prewedding-photo',
    slug: 'pre-wedding',
    name: 'Pre-wedding',
    category: 'Pre-wedding',
    shortDescription: 'Chụp pre-wedding với không gian, thời trang và ánh sáng đẹp mắt.',
    description: 'Pre-wedding mang đến trải nghiệm chụp ảnh lãng mạn, sáng tạo và dễ thương với nhiều concept phù hợp với phong cách của bạn.',
    priceFrom: 6400000,
    duration: '3-4 giờ',
    image: '/assets/crossed-hands-white.jpg',
    deliverables: ['80+ ảnh đã chỉnh sửa', 'Concept riêng', 'Bài chụp tuyệt đẹp', 'Đề xuất location'],
    isFeatured: true,
  },
  {
    id: 'birthday-photo',
    slug: 'anh-sinh-nhat',
    name: 'Sinh nhật',
    category: 'Sinh nhật',
    shortDescription: 'Chụp hình sinh nhật, portrait và khoảnh khắc vui vẻ trong ngày đặc biệt.',
    description: 'Gói chụp hình sinh nhật giúp lưu giữ những khoảnh khắc vui tươi, ngập tràn ánh sáng và tạo bộ ảnh đẹp cho gia đình và bạn bè.',
    priceFrom: 4200000,
    duration: '2-3 giờ',
    image: '/assets/detail-kalire.jpg',
    deliverables: ['40+ ảnh', 'Cắt gọn theo concept', 'Ảnh hậu trường', 'Bộ ảnh online'],
    isFeatured: false,
  },
  {
    id: 'event-photo',
    slug: 'anh-su-kien',
    name: 'Sự kiện',
    category: 'Sự kiện',
    shortDescription: 'Ghi lại mọi khoảnh khắc lớn nhỏ của sự kiện bạn tổ chức.',
    description: 'Dịch vụ chụp ảnh sự kiện giúp ghi lại không khí, cảm xúc và các chi tiết quan trọng của buổi tiệc, hội nghị, ra mắt hoặc sự kiện doanh nghiệp.',
    priceFrom: 5500000,
    duration: '4-8 giờ',
    image: '/assets/process-applying.jpg',
    deliverables: ['Ảnh sự kiện theo timeline', 'Bộ ảnh dạng event', 'Mẫu chỉnh ảnh nhanh', 'Tặng ảnh highlight'],
    isFeatured: true,
  },
  {
    id: 'portrait-photo',
    slug: 'chan-dung',
    name: 'Chân dung',
    category: 'Chân dung',
    shortDescription: 'Chụp chân dung cá nhân với phong cách hiện đại và tự nhiên.',
    description: 'Chụp chân dung là cách để thể hiện phong cách cá nhân, sự tự tin và những điểm sáng của mỗi người.',
    priceFrom: 3000000,
    duration: '1-2 giờ',
    image: '/assets/floral-vine-hands.jpg',
    deliverables: ['20+ ảnh', 'Hình ảnh đẹp chuẩn social', 'Tư vấn phong cách', 'Bộ ảnh online'],
    isFeatured: false,
  },
]

export const formatVnd = (value) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
