export const restaurants = [
  {
    id: 'unam-garden',
    slug: 'unam-garden',
    name: 'UnAm Garden',
    shortDescription: 'Không gian ngoài trời ấm áp cho tiệc gia đình, sự kiện nhỏ và truyền thống.',
    description: 'UnAm Garden là lựa chọn lý tưởng cho những buổi tiệc thân mật, lễ cưới gia đình và sự kiện ngoài trời với không gian xanh mát, ánh sáng dịu và thực đơn đa dạng.',
    address: '203 Lê Văn Hưu, Quận 1, TP.HCM',
    capacityMin: 80,
    capacityMax: 220,
    priceFrom: 4500000,
    image: '/assets/hands-babysbreath.jpg',
    gallery: ['/assets/hands-babysbreath.jpg', '/assets/floral-vine-hands.jpg', '/assets/process-applying.jpg'],
    amenities: ['Sân ngoài trời', 'Khu vực chụp hình', 'Trang trí riêng', 'Ăn uống theo gói'],
    isFeatured: true,
  },
  {
    id: 'unam-riverside',
    slug: 'unam-riverside',
    name: 'UnAm Riverside',
    shortDescription: 'Khung cảnh hồ nước và không gian hiện đại cho sự kiện thân thuộc.',
    description: 'UnAm Riverside kết hợp kiến trúc hiện đại, tầm nhìn thoáng đãng và không gian đa năng, phù hợp cho tiệc cocktail, sinh nhật, chào hỏi và các sự kiện cộng đồng.',
    address: '88 Nguyễn Hữu Thọ, Quận 7, TP.HCM',
    capacityMin: 120,
    capacityMax: 280,
    priceFrom: 5200000,
    image: '/assets/detail-french-cream.jpg',
    gallery: ['/assets/detail-french-cream.jpg', '/assets/bride-jhumar.jpg', '/assets/crossed-hands-white.jpg'],
    amenities: ['View hồ', 'Phòng VIP', 'Sân khấu', 'Quầy đồ uống'],
    isFeatured: true,
  },
  {
    id: 'unam-grand-hall',
    slug: 'unam-grand-hall',
    name: 'UnAm Grand Hall',
    shortDescription: 'Không gian rộng lớn, sang trọng cho sự kiện lớn và tiệc tối.',
    description: 'UnAm Grand Hall là nơi lý tưởng cho các sự kiện lớn với thiết kế sang trọng, không gian rộng và tiện ích phục vụ chuyên nghiệp cho tiệc cưới và gala.',
    address: '16 Nguyễn Văn Linh, Quận 7, TP.HCM',
    capacityMin: 180,
    capacityMax: 420,
    priceFrom: 7000000,
    image: '/assets/bride-jhumar.jpg',
    gallery: ['/assets/bride-jhumar.jpg', '/assets/detail-kalire.jpg', '/assets/hands-babysbreath.jpg'],
    amenities: ['Sảnh lớn', 'Sân khấu đài phun', 'Phòng thay đồ', 'Tư vấn thực đơn'],
    isFeatured: true,
  },
]

export const formatVnd = (value) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
